MODEL:
  model_names: HSPFormer_PosEmbedd
  # model_names: HSPFormer_PatchEmbedd
  model_spec: hsp_v2_b2
  
  # model_names: Segformer_PosEmbedd
  # model_spec: mitV2_b2
  
  load_Pretraining: 'pretraining/pvt_v2_b2.pth'

DATASET:
  dataset: KITTI360
  name: KITTI360
  dataroot: 'data/KITTI360'
  ignore_index: 255
  num_labels: 19

TRAIN:
  nepoch: 40
  batch_size: 6
  size: [384,1408]
  num_workers: 6
  eval_interval: 5
  checkpoints_dir: 'checkpoints'
  node: 2

OPTIMIZER:
  lr            : 0.00006
  weight_decay  : 0.05

SCHEDULER:
  warmup_epoch: 5
  lr_warmup: linear
  warmup_ratio: 0.000001

continue_train: False
